# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'ViChat'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/favico.png'
- name: LOGO
  value: '/brand-assets/logo.png'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.png'
- name: BRAND_URL
  value: 'https://vitechgroup.vn'
- name: WIDGET_BRAND_URL
  value: 'https://vitechgroup.vn'
- name: BRAND_NAME
  value: 'ViChat'
- name: TERMS_URL
  value: 'https://vitechgroup.vn'
- name: PRIVACY_URL
  value: 'https://vitechgroup.vn'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
